letitgo:
  name: sawsh
  description: SSH wrapper for aws to make your life easier.
  actions:
    - type: changelog
      file: CHANGELOG.md

    - type: archive
      source: "./build/bin/*"
      target: "./build/pkg/"
      extras:
        - "LICENSE"
        - "CHANGELOG.md"

    - type: githubrelease
      assets:
        - ./build/pkg/*

    - type: homebrew
      homepage: https://github.com/NoUseFreak/sawsh
      url: https://github.com/NoUseFreak/sawsh/releases/download/{{ .Version }}/darwin_amd64.zip
      version: "{{ .Version }}"
      tap:
        url: git@github.com:NoUseFreak/homebrew-brew.git
      test: system "#{bin}/{{ .Name }} -h"
